plugins {
    id 'com.github.hierynomus.license' version '0.15.0'
    id 'com.gradle.plugin-publish' version '2.1.1'
    id 'groovy'
    id 'java-gradle-plugin'
    //id 'jacoco'
}

group = 'com.stehno.gradle'
version = '0.3.0'

sourceCompatibility = 17
targetCompatibility = 17

sourceSets {
    functionalTest {
        groovy {
            srcDir file('src/functionalTest/groovy')
        }
        resources {
            srcDir file('src/functionalTest/resources')
        }
        //compileClasspath += sourceSets.main.output + configurations.testRuntime
        //runtimeClasspath += output + compileClasspath
    }
}

/*task functionalTest(type: Test) {
    testClassesDir = sourceSets.functionalTest.output.classesDir
    classpath = sourceSets.functionalTest.runtimeClasspath
}*/

//check.dependsOn functionalTest

gradlePlugin {
    testSourceSets sourceSets.functionalTest
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:6.0.3"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    testImplementation ('org.spockframework:spock-core:2.4-groovy-3.0')

    /*functionalTestCompile('org.spockframework:spock-core:1.0-groovy-2.4') {
        exclude module: 'groovy-all'
    }
    functionalTestCompile('org.mock-server:mockserver-client-java:3.10.4') {
        exclude group: 'ch.qos.logback', module: 'logback-classic'
    }
    functionalTestCompile('org.mock-server:mockserver-netty:3.10.4') {
        exclude group: 'ch.qos.logback', module: 'logback-classic'
    }*/
}

test {
    useJUnitPlatform()
}

/*license {
    header rootProject.file('license_header.txt')
    ext.year = Calendar.instance.get(Calendar.YEAR)
}*/

/*pluginBundle {
    website = 'http://cjstehno.github.io/dependency-checker/'
    vcsUrl = 'https://github.com/cjstehno/dependency-checker'
    description = 'Gradle plugin to aid in managing dependencies.'
    tags = ['gradle', 'groovy']

    plugins {
        dependencyCheckerPlugin {
            id = 'com.stehno.gradle.dependency-checker'
            displayName = 'Gradle Dependency Checker Plugin'
        }
    }
}*/
